version: '3.7'

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysql-labs-communication
    restart: always
    environment:
      TZ: "America/Sao_Paulo"
      MYSQL_DATABASE: ${MGR_MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MGR_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MGR_MYSQL_USER}
      MYSQL_PASSWORD: ${MGR_MYSQL_PASSWORD}
    networks:
      - mgr-network
  rabbitmq:
    container_name: rabbitmq-labs-communication
    image: rabbitmq:3-management
    healthcheck:
      test: [ "CMD", "nc", "-z", "rabbitmq", "5672" ]
      interval: 30s
      timeout: 10s
      retries: 5
    expose:
      - 15672
      - 5672
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - mgr-network
  labs_communication_api:
    build:
      dockerfile: ./docker/labs-communication-api.dockerfile
      context: .
    image: mgr/labs-communication-api
    container_name: labs-communication-api
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      TZ: "America/Sao_Paulo"
      SPRING_MYSQL_DATABASE: ${MGR_MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MGR_MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MGR_MYSQL_PASSWORD}
      SPRING_RABBITMQ_ADDRESSES: amqp://guest:guest@rabbitmq:5672/
    links:
      - rabbitmq:rabbitmq
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
      - rabbitmq
    networks:
      - mgr-network

networks:
  mgr-network:
    name: mgr-network
    driver: bridge


