version: '3.7'

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysql-labs-communication
    restart: always
    environment:
      TZ: "America/Sao_Paulo"
      MYSQL_DATABASE: ${MGR_MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MGR_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MGR_MYSQL_USER}
      MYSQL_PASSWORD: ${MGR_MYSQL_PASSWORD}
    networks:
      - mgr-network
  rabbit:
    image: rabbitmq:3-management
    container_name: rabbitmq-labs-communication
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: vhost_rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mgr-network
  labs_communication_api:
    build:
      dockerfile: ./docker/labs-communication-api.dockerfile
      context: .
    image: mgr/labs-communication-api
    container_name: labs-communication-api
    restart: on-failure
    environment:
      TZ: "America/Sao_Paulo"
      SPRING_MYSQL_DATABASE: ${MGR_MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MGR_MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MGR_MYSQL_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
      - rabbit
    networks:
      - mgr-network

networks:
  mgr-network:
    name: mgr-network
    driver: bridge


