server:
  port: 8080
  servlet:
    context-path: /api-communications

spring:
  profiles:
    active: prod

  application:
    version: @project.version@
    name: @project.name@
    description: @project.description@
    artifact-id: @project.artifactId@

  datasource:
    url: jdbc:mysql://mysqldb:3306/${SPRING_MYSQL_DATABASE}?autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    request:
      host: localhost
      port: 5672
      username: guest
      password: guest
      queue:
        producer: qu.producer.message
      exchange:
        producer: ex.producer.message
      routing-key:
        producer: rk.producer.message
      dead-letter:
        producer: dl.producer.message
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
