server:
  port: 8081



spring:

  datasource:
    url: "jdbc:h2:mem:labs_communication_db"
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  flyway:
    enabled: false
    baseline-on-migrate: false
    validate-on-migrate: false

  h2:
    console:
      enabled: true
      path: "/h2-console"

