SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `labs_communication_db` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE IF NOT EXISTS labs_communication_db.recipients (
    id BIGINT(20) NOT NULL AUTO_INCREMENT,
    recipient varchar(255) NOT NULL,
    PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS labs_communication_db.messages (
    id BIGINT(20) NOT NULL AUTO_INCREMENT,
    date_time_schedule TIMESTAMP NOT NULL,
    message VARCHAR(255) NOT NULL,
    message_state VARCHAR(10) NOT NULL,
    message_type varchar(10) NOT NULL,
    id_recipient bigint NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP ,
    modified_at DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT messages_recipients_id_fk
        FOREIGN KEY (id_recipient)
        REFERENCES labs_communication_db.recipients (id))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;